# Base Link style
url: "http://blog.beanmr.com"
baseurl: ""
permalink: /:year/:month/:day/:title/
# Engine
markdown: kramdown
highlighter: rouge
# paginate
paginate: 10
paginate_path: ":num"
# About ME
title: "BeanMr.代码作坊"
description: "爱代码、爱生活的老猴子"
email: "beanmrx@gmail.com"
github_username:  "beanmr"
# support feature
swiftype_searchId: "fAGFEb37RW1JWLSAKW6j"
duoshuo: BeanMr
stat_baidu: c199e990e3c84b0b1047773457ba7222
# license
license: "http://creativecommons.org/licenses/by-sa/3.0/cn/"
# other
media_repos: "/static/media/"
gems: [jekyll-paginate]