baseurl: ""
permalink: /:year/:month/:day/:title/

markdown: kramdown
highlighter: pygments

paginate: 10
paginate_path: ":num"

title: "BeanMr.代码作坊"
description: "爱代码、爱生活的老猴子"
email: "beanmrx@gmail.com"
github_username:  "beanmr"

swiftype_searchId: "epMSXCyxABpMNYo9fdNt"
duoshuo: BeanMr
stat_baidu: c199e990e3c84b0b1047773457ba7222

license: "http://creativecommons.org/licenses/by-sa/3.0/cn/"