markdown: redcarpet
permalink: /:title/
url: http://blog.beanmr.com
name: BeanMr.Blog
author: BeanMr.
qq: 
email: QmVhbk1yeEBnbWFpbC5jb20=
duoshuo: BeanMr
beian: 
cnzz: 1253416671
weibo: 5333831917
github: BeanMr
pygments: true
safe: true
encoding: utf-8
paginate: 20
about: "这里是 BeanMr.的个人博客"
