markdown: redcarpet
permalink: /:title/
url: http://blog.estonnet.com
name: Eston>Net
author: Eston
qq: 
email: ZXN0b25mdW5neEBnbWFpbC5jb20=
duoshuo: eston
beian: 
cnzz: 1000117189
weibo: 
github: estonfung
pygments: true
safe: true
encoding: utf-8
paginate: 20
about: "这里是 Eston 的个人博客"
