# Base Link style
#url: "http://blog.beanmr.com"
# used for sitemap
publish_url: "http://blog.beanmr.com"
baseurl: ""
permalink: /:year/:month/:day/:title/
# Engine
markdown: kramdown
highlighter: rouge
# paginate
paginate: 10
paginate_path: ":num"
# About ME
title: "BeanMr.代码作坊"
description: "互联网是一门实践性科学"
email: "beanmrx@gmail.com"
github_username:  "beanmr"
# support feature
swiftype_searchId: "fAGFEb37RW1JWLSAKW6j"
duoshuo: BeanMr
stat_baidu: c199e990e3c84b0b1047773457ba7222
baidu_share: 89860593
# bshare: 7e6f50e6-622a-48d7-b75f-d4eb366729d5
# bshare_to: "'sinaminiblog','weixin','gplus','qzone','qqmb','renren','evernote','youdaonote','twitter','linkedin','facebook'"
# license
license: "http://creativecommons.org/licenses/by-sa/3.0/cn/"
# other
media_repos: "http://7xq06s.com1.z0.glb.clouddn.com/"
gems: [jekyll-paginate]